[package]
name = "nebulakey-host"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.8.1"
tokio = { version = "1.49", features = ["rt-multi-thread", "macros", "time"] }


[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Media", "Media_Control"] }
